spring:
    profiles:
        active: local


server:
    error:
        include-message: always


management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            roles: USER
            show-details: always
            #show-details: when_authorized
    health:
        diskspace:
            enabled: true
        db:
            enabled: true


---
spring:
    config:
        activate:
            on-profile: local
    datasource:
        hikari:
            idle-timeout: 90000
            maximum-pool-size: 10
            minimum-idle: 2
        password: admin
        url: jdbc:postgresql://localhost:5432/gymcrmdb
        username: postgres
        validationQuery: SELECT 1
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        defer-datasource-initialization: true
        format_sql: true
        hibernate:
            ddl-auto: create-drop
        highlight_sql: true
        show-sql: true
    sql:
        init:
            mode: always
logging:
    level:
        com:
            epam:
                gymcrm: DEBUG


---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        hikari:
            idle-timeout: 90000
            maximum-pool-size: 10
            minimum-idle: 2
        password: admin
        url: jdbc:postgresql://localhost:5432/gymcrmdb
        username: postgres
        validationQuery: SELECT 1
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        defer-datasource-initialization: true
        format_sql: true
        hibernate:
            ddl-auto: update
        highlight_sql: true
        show-sql: true
    sql:
        init:
            mode: always
logging:
    level:
        com:
            epam:
                gymcrm: DEBUG
---
spring:
    config:
        activate:
            on-profile: stg
    datasource:
        hikari:
            idle-timeout: 90000
            maximum-pool-size: 10
            minimum-idle: 2
        password: admin
        url: jdbc:postgresql://localhost:5432/gymcrmdb
        username: postgres
        validationQuery: SELECT 1
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        defer-datasource-initialization: true
        format_sql: true
        hibernate:
            ddl-auto: validate
        highlight_sql: true
        show-sql: true
    sql:
        init:
            mode: always

logging:
    level:
        com:
            epam:
                gymcrm: INFO

---
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        hikari:
            idle-timeout: 90000
            maximum-pool-size: 10
            minimum-idle: 2
        password: admin
        url: jdbc:postgresql://localhost:5432/gymcrmdb
        username: postgres
        validationQuery: SELECT 1
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        defer-datasource-initialization: true
        format_sql: true
        hibernate:
            ddl-auto: none
        highlight_sql: true
        show-sql: true
    sql:
        init:
            mode: always

logging:
    level:
        com:
            epam:
                gymcrm: INFO
