spring:
    config:
        activate:
            on-profile: stg
    datasource:
        hikari:
            idle-timeout: 90000
            maximum-pool-size: 10
            minimum-idle: 2
        password: admin
        url: jdbc:postgresql://localhost:5432/gymcrmdb-stg
        username: postgres
        validationQuery: SELECT 1
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        defer-datasource-initialization: true
        format_sql: true
        hibernate:
            ddl-auto: validate
        highlight_sql: true
        show-sql: true
    sql:
        init:
            mode: always

logging:
    level:
        com:
            epam:
                gymcrm: INFO