spring:
    profiles:
        active: local


server:
    error:
        include-message: always


management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            roles: USER
            show-details: always
            #show-details: when_authorized
    health:
        diskspace:
            enabled: true
        db:
            enabled: true



